timeout: 5000
doh:
  enable: false
dns:
  udp:
    enable: true
    port: 5053
  tcp:
    enable: true
    port: 5053
recursive:
  enable: true
debug: true
database:
  name: lurker.db
  path: ./db-test
