timeout: 5000
doh:
  enable: true
dns:
  udp:
    enable: true
    port: 5053
  tcp:
    enable: true
    port: 5053
recursive:
  enable: true
  useLocalDns: false
  upstream:
    - host: 223.5.5.5
debug: true
database:
  name: lurker.db
  path: ./db-test
