name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Metadata generation
        shell: bash
        run: |
          ./gradlew compileCommonMainKotlinMetadata

      - name: Build with Gradle
        shell: bash
        run: |
          ./gradlew github
